### ISSUE TITLE
As a developer i want to delete the relationship between likes and cheeps when a cheep is deleted

### ISSUE THREAD

**Issue by RasmusAChr** [ITU-BDSA2024-GROUP7/Chirp#209]
When we implemented like and dislike, we didn't take into account that the relations between a like / dislike and a cheep should be deleted when the cheep is deleted. The same goes for when deleting an account.

Furthermore I'm not sure if this is also a problem for the reactions and comments on a cheep.

**Comment by niko391a** [comment]
Our current implementation of DeleteCheep() in CheepRepository.cs and DeleteUser() in AuthorRepository.cs, handles this. This is because:
- Like and Reaction both have a CheepId foreign key, which links them to the Cheep entity.
- By default, EF Core sets up cascade delete behavior for relationships where a principal entity (Cheep) has dependent entities (Like, Reaction).
